services:
  postgres:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d security"]
      interval: 5s
      timeout: 5s
      retries: 10
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: security
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 412m
    cpus: 0.2
    restart: always

  app:
    build: . 
    container_name: jcbc-sd
    mem_limit: 412m
    cpus: 0.6
    restart: always
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/security
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npx prisma db seed &&
        npm start
      "

volumes:
  postgres_data: